from gym_minigrid.envs.empty import *
from gym_minigrid.envs.doorkey import *
from gym_minigrid.envs.multiroom import *
from gym_minigrid.envs.fetch import *
from gym_minigrid.envs.gotoobject import *
from gym_minigrid.envs.gotodoor import *
from gym_minigrid.envs.putnear import *
from gym_minigrid.envs.lockedroom import *
from gym_minigrid.envs.playground_v0 import *
from gym_minigrid.envs.redbluedoors import *
from gym_minigrid.envs.unsafe import *
from gym_minigrid.envs.unsafeDoor import *
from gym_minigrid.envs.deadend import *
from gym_minigrid.envs.deadendWater import *
from gym_minigrid.envs.bigEnv import *
from gym_minigrid.envs.doorEnv import *
from gym_minigrid.envs.doorWaterEnv import *
from gym_minigrid.envs.safety import *
from gym_minigrid.envs.cleaningEnv import *
from gym_minigrid.envs.miniclean import *
from gym_minigrid.envs.bigcleanEnv import *
from gym_minigrid.envs.randoms.randomenv9660 import *
from gym_minigrid.envs.randoms.randomenv2133 import *
from gym_minigrid.envs.wa6_grid6 import *
from gym_minigrid.envs.dnd2_grid6 import *
from gym_minigrid.envs.li_grid6 import *
from gym_minigrid.envs.lighttest import *
from gym_minigrid.envs.randoms.randomenv5338 import *
from gym_minigrid.envs.randoms.randomenv3658 import *
from gym_minigrid.envs.randoms.randomenv549 import *
from gym_minigrid.envs.randoms.randomenv985 import *
from gym_minigrid.envs.randoms.randomenv4115 import *
from gym_minigrid.envs.randoms.randomenv5939 import *
from gym_minigrid.envs.randoms.randomenv7185 import *
from gym_minigrid.envs.randoms.randomenv7962 import *
from gym_minigrid.envs.randoms.randomenv1588 import *
from gym_minigrid.envs.randoms.randomenv5862 import *
from gym_minigrid.envs.randoms.randomenv1398 import *
from gym_minigrid.envs.randoms.randomenv285 import *
from gym_minigrid.envs.randoms.randomenv3874 import *
from gym_minigrid.envs.randoms.randomenv7584 import *
from gym_minigrid.envs.randoms.randomenv5419 import *
from gym_minigrid.envs.randoms.randomenv3084 import *
from gym_minigrid.envs.randoms.randomenv2489 import *
from gym_minigrid.envs.randoms.randomenv809 import *
from gym_minigrid.envs.randoms.randomenv1308 import *
from gym_minigrid.envs.randoms.randomenv5090 import *
from gym_minigrid.envs.randoms.randomenv1284 import *
from gym_minigrid.envs.randoms.randomenv4060 import *
from gym_minigrid.envs.randoms.randomenv7765 import *
from gym_minigrid.envs.randoms.randomenv5575 import *
from gym_minigrid.envs.randoms.randomenv4746 import *
from gym_minigrid.envs.randoms.randomenv1120 import *
from gym_minigrid.envs.randoms.randomenv5004 import *
from gym_minigrid.envs.randoms.randomenv1505 import *
from gym_minigrid.envs.randoms.randomenv3177 import *
from gym_minigrid.envs.randoms.randomenv3770 import *
from gym_minigrid.envs.randoms.randomenv9464 import *
from gym_minigrid.envs.randoms.randomenv5986 import *
from gym_minigrid.envs.randoms.randomenv6526 import *
from gym_minigrid.envs.randoms.randomenv6644 import *
from gym_minigrid.envs.randoms.randomenv1276 import *
from gym_minigrid.envs.randoms.randomenv3108 import *
from gym_minigrid.envs.randoms.randomenv4135 import *
from gym_minigrid.envs.randoms.randomenv3418 import *
from gym_minigrid.envs.randoms.randomenv2944 import *
from gym_minigrid.envs.randoms.randomenv6488 import *
from gym_minigrid.envs.randoms.randomenv4803 import *
from gym_minigrid.envs.randoms.randomenv2177 import *
from gym_minigrid.envs.randoms.randomenv2870 import *
from gym_minigrid.envs.randoms.randomenv2285 import *
from gym_minigrid.envs.randoms.randomenv562 import *
from gym_minigrid.envs.randoms.randomenv5853 import *
from gym_minigrid.envs.randoms.randomenv9948 import *
from gym_minigrid.envs.randoms.randomenv2433 import *
from gym_minigrid.envs.randoms.randomenv8625 import *
from gym_minigrid.envs.randoms.randomenv7903 import *
from gym_minigrid.envs.randoms.randomenv8491 import *
from gym_minigrid.envs.randoms.randomenv5974 import *
from gym_minigrid.envs.randoms.randomenv4978 import *
from gym_minigrid.envs.randoms.randomenv4654 import *
from gym_minigrid.envs.randoms.randomenv715 import *
from gym_minigrid.envs.randoms.randomenv7020 import *
from gym_minigrid.envs.randoms.randomenv2259 import *
from gym_minigrid.envs.randoms.randomenv2727 import *
from gym_minigrid.envs.randoms.randomenv664 import *
from gym_minigrid.envs.randoms.randomenv3705 import *
from gym_minigrid.envs.randoms.randomenv8567 import *
from gym_minigrid.envs.randoms.randomenv8556 import *
from gym_minigrid.envs.randoms.randomenv3695 import *
from gym_minigrid.envs.randoms.randomenv8294 import *
from gym_minigrid.envs.randoms.randomenv5536 import *
from gym_minigrid.envs.randoms.randomenv2014 import *
from gym_minigrid.envs.randoms.randomenv1195 import *
from gym_minigrid.envs.randoms.randomenv1962 import *
from gym_minigrid.envs.randoms.randomenv816 import *
from gym_minigrid.envs.randoms.randomenv694 import *
from gym_minigrid.envs.randoms.randomenv2422 import *
from gym_minigrid.envs.randoms.randomenv3054 import *
from gym_minigrid.envs.randoms.randomenv7326 import *
from gym_minigrid.envs.randoms.randomenv2052 import *
from gym_minigrid.envs.randoms.randomenv3915 import *
from gym_minigrid.envs.randoms.randomenv6227 import *
from gym_minigrid.envs.randoms.randomenv9809 import *
from gym_minigrid.envs.randoms.randomenv8373 import *
from gym_minigrid.envs.randoms.randomenv1773 import *
from gym_minigrid.envs.randoms.randomenv8240 import *
from gym_minigrid.envs.randoms.randomenv2723 import *
from gym_minigrid.envs.randoms.randomenv6697 import *
from gym_minigrid.envs.randoms.randomenv5996 import *
from gym_minigrid.envs.randoms.randomenv9888 import *
from gym_minigrid.envs.randoms.randomenv9090 import *
from gym_minigrid.envs.randoms.randomenv4321 import *
from gym_minigrid.envs.randoms.randomenv2804 import *
from gym_minigrid.envs.randoms.randomenv4278 import *
from gym_minigrid.envs.randoms.randomenv8908 import *
from gym_minigrid.envs.randoms.randomenv671 import *
from gym_minigrid.envs.randoms.randomenv7773 import *
from gym_minigrid.envs.randoms.randomenv5392 import *
from gym_minigrid.envs.randoms.randomenv4712 import *
from gym_minigrid.envs.randoms.randomenv4211 import *
from gym_minigrid.envs.randoms.randomenv1286 import *
from gym_minigrid.envs.randoms.randomenv7980 import *
from gym_minigrid.envs.randoms.randomenv7079 import *
from gym_minigrid.envs.randoms.randomenv433 import *
from gym_minigrid.envs.randoms.randomenv506 import *
from gym_minigrid.envs.randoms.randomenv6993 import *
from gym_minigrid.envs.randoms.randomenv1977 import *
from gym_minigrid.envs.randoms.randomenv5081 import *
from gym_minigrid.envs.randoms.randomenv2721 import *
from gym_minigrid.envs.randoms.randomenv3545 import *
from gym_minigrid.envs.randoms.randomenv8671 import *
from gym_minigrid.envs.randoms.randomenv42 import *
from gym_minigrid.envs.randoms.randomenv4834 import *
from gym_minigrid.envs.randoms.randomenv9374 import *
from gym_minigrid.envs.randoms.randomenv4498 import *
from gym_minigrid.envs.randoms.randomenv2708 import *
from gym_minigrid.envs.randoms.randomenv199 import *
from gym_minigrid.envs.randoms.randomenv5018 import *
from gym_minigrid.envs.randoms.randomenv7650 import *
from gym_minigrid.envs.randoms.randomenv5364 import *
from gym_minigrid.envs.randoms.randomenv9021 import *
from gym_minigrid.envs.randoms.randomenv1363 import *
from gym_minigrid.envs.randoms.randomenv2283 import *
from gym_minigrid.envs.randoms.randomenv8244 import *
from gym_minigrid.envs.randoms.randomenv7139 import *
from gym_minigrid.envs.randoms.randomenv6309 import *
from gym_minigrid.envs.randoms.randomenv6517 import *
from gym_minigrid.envs.randoms.randomenv8567 import *
from gym_minigrid.envs.randoms.randomenv7022 import *
from gym_minigrid.envs.randoms.randomenv1427 import *
from gym_minigrid.envs.randoms.randomenv1728 import *
from gym_minigrid.envs.randoms.randomenv3012 import *
from gym_minigrid.envs.randoms.randomenv3423 import *
from gym_minigrid.envs.randoms.randomenv6125 import *
from gym_minigrid.envs.randoms.randomenv2546 import *
from gym_minigrid.envs.randoms.randomenv5370 import *
from gym_minigrid.envs.randoms.randomenv9984 import *
from gym_minigrid.envs.randoms.randomenv3470 import *
from gym_minigrid.envs.randoms.randomenv4891 import *
from gym_minigrid.envs.randoms.randomenv5357 import *
from gym_minigrid.envs.randoms.randomenv7029 import *
from gym_minigrid.envs.randoms.randomenv1665 import *
from gym_minigrid.envs.randoms.randomenv9378 import *
from gym_minigrid.envs.randoms.randomenv2375 import *
from gym_minigrid.envs.randoms.randomenv4339 import *
from gym_minigrid.envs.randoms.randomenv8886 import *
from gym_minigrid.envs.randoms.randomenv9795 import *
from gym_minigrid.envs.randoms.randomenv2552 import *
from gym_minigrid.envs.randoms.randomenv9321 import *
from gym_minigrid.envs.randoms.randomenv8395 import *
from gym_minigrid.envs.randoms.randomenv4978 import *
from gym_minigrid.envs.randoms.randomenv672 import *
from gym_minigrid.envs.randoms.randomenv681 import *
from gym_minigrid.envs.randoms.randomenv4970 import *
from gym_minigrid.envs.randoms.randomenv9086 import *
from gym_minigrid.envs.randoms.randomenv1797 import *
from gym_minigrid.envs.randoms.randomenv3061 import *
from gym_minigrid.envs.randoms.randomenv1286 import *
from gym_minigrid.envs.randoms.randomenv3801 import *
from gym_minigrid.envs.randoms.randomenv5696 import *
from gym_minigrid.envs.randoms.randomenv464 import *
from gym_minigrid.envs.randoms.randomenv2940 import *
from gym_minigrid.envs.randoms.randomenv1866 import *
from gym_minigrid.envs.randoms.randomenv9964 import *
from gym_minigrid.envs.randoms.randomenv7373 import *
from gym_minigrid.envs.randoms.randomenv3516 import *
from gym_minigrid.envs.randoms.randomenv7698 import *
from gym_minigrid.envs.randoms.randomenv9309 import *
from gym_minigrid.envs.randoms.randomenv3066 import *
from gym_minigrid.envs.randoms.randomenv5315 import *
from gym_minigrid.envs.randoms.randomenv2677 import *
from gym_minigrid.envs.randoms.randomenv5712 import *
from gym_minigrid.envs.randoms.randomenv5920 import *
from gym_minigrid.envs.randoms.randomenv9058 import *
from gym_minigrid.envs.randoms.randomenv5064 import *
from gym_minigrid.envs.randoms.randomenv1311 import *
from gym_minigrid.envs.randoms.randomenv8432 import *
from gym_minigrid.envs.randoms.randomenv3331 import *
from gym_minigrid.envs.randoms.randomenv3273 import *
from gym_minigrid.envs.randoms.randomenv2612 import *
from gym_minigrid.envs.randoms.randomenv1598 import *
from gym_minigrid.envs.randoms.randomenv8600 import *
from gym_minigrid.envs.randoms.randomenv4782 import *
from gym_minigrid.envs.randoms.randomenv6465 import *
from gym_minigrid.envs.randoms.randomenv962 import *
from gym_minigrid.envs.randoms.randomenv8832 import *
from gym_minigrid.envs.randoms.randomenv8603 import *
from gym_minigrid.envs.randoms.randomenv5577 import *
from gym_minigrid.envs.randoms.randomenv7516 import *
from gym_minigrid.envs.randoms.randomenv3606 import *
from gym_minigrid.envs.randoms.randomenv7190 import *
from gym_minigrid.envs.randoms.randomenv4217 import *
from gym_minigrid.envs.randoms.randomenv9781 import *
from gym_minigrid.envs.randoms.randomenv412 import *
from gym_minigrid.envs.randoms.randomenv8065 import *
from gym_minigrid.envs.randoms.randomenv5713 import *
from gym_minigrid.envs.randoms.randomenv5568 import *
from gym_minigrid.envs.randoms.randomenv4504 import *
from gym_minigrid.envs.randoms.randomenv847 import *
from gym_minigrid.envs.randoms.randomenv1542 import *
from gym_minigrid.envs.randoms.randomenv8103 import *
from gym_minigrid.envs.randoms.randomenv1414 import *
from gym_minigrid.envs.randoms.randomenv3851 import *
from gym_minigrid.envs.randoms.randomenv8621 import *
from gym_minigrid.envs.randoms.randomenv9270 import *
from gym_minigrid.envs.randoms.randomenv8212 import *
from gym_minigrid.envs.randoms.randomenv7415 import *
from gym_minigrid.envs.randoms.randomenv1266 import *
from gym_minigrid.envs.randoms.randomenv589 import *
from gym_minigrid.envs.randoms.randomenv7954 import *
from gym_minigrid.envs.randoms.randomenv286 import *
from gym_minigrid.envs.randoms.randomenv9577 import *
from gym_minigrid.envs.randoms.randomenv7895 import *
from gym_minigrid.envs.randoms.randomenv2740 import *
from gym_minigrid.envs.randoms.randomenv1858 import *
from gym_minigrid.envs.randoms.randomenv1119 import *
from gym_minigrid.envs.randoms.randomenv7721 import *
from gym_minigrid.envs.randoms.randomenv2763 import *
from gym_minigrid.envs.randoms.randomenv5940 import *
from gym_minigrid.envs.randoms.randomenv9578 import *
from gym_minigrid.envs.randoms.randomenv7860 import *
from gym_minigrid.envs.randoms.randomenv5822 import *
from gym_minigrid.envs.randoms.randomenv293 import *
from gym_minigrid.envs.randoms.randomenv8817 import *
from gym_minigrid.envs.randoms.randomenv6913 import *
from gym_minigrid.envs.randoms.randomenv4176 import *
from gym_minigrid.envs.randoms.randomenv7616 import *
from gym_minigrid.envs.randoms.randomenv9258 import *
from gym_minigrid.envs.randoms.randomenv7606 import *
from gym_minigrid.envs.randoms.randomenv1122 import *
from gym_minigrid.envs.randoms.randomenv4386 import *
from gym_minigrid.envs.randoms.randomenv6144 import *
from gym_minigrid.envs.randoms.randomenv8559 import *
from gym_minigrid.envs.randoms.randomenv8660 import *
from gym_minigrid.envs.randoms.randomenv749 import *
from gym_minigrid.envs.randoms.randomenv6419 import *
from gym_minigrid.envs.randoms.randomenv8191 import *
from gym_minigrid.envs.randoms.randomenv9241 import *
from gym_minigrid.envs.randoms.randomenv2188 import *
from gym_minigrid.envs.randoms.randomenv9462 import *
from gym_minigrid.envs.randoms.randomenv2283 import *
from gym_minigrid.envs.randoms.randomenv4102 import *
from gym_minigrid.envs.randoms.randomenv1796 import *
from gym_minigrid.envs.randoms.randomenv9311 import *
from gym_minigrid.envs.randoms.randomenv6079 import *
from gym_minigrid.envs.randoms.randomenv5445 import *
from gym_minigrid.envs.randoms.randomenv6587 import *
from gym_minigrid.envs.randoms.randomenv1875 import *
from gym_minigrid.envs.randoms.randomenv1338 import *
from gym_minigrid.envs.randoms.randomenv2845 import *
from gym_minigrid.envs.randoms.randomenv4795 import *
from gym_minigrid.envs.randoms.randomenv6034 import *
from gym_minigrid.envs.randoms.randomenv1738 import *
from gym_minigrid.envs.randoms.randomenv9503 import *
from gym_minigrid.envs.randoms.randomenv1287 import *
from gym_minigrid.envs.randoms.randomenv8151 import *
from gym_minigrid.envs.randoms.randomenv3559 import *
from gym_minigrid.envs.randoms.randomenv6072 import *
from gym_minigrid.envs.randoms.randomenv5098 import *
from gym_minigrid.envs.randoms.randomenv5194 import *
from gym_minigrid.envs.randoms.randomenv166 import *
from gym_minigrid.envs.randoms.randomenv9354 import *
from gym_minigrid.envs.randoms.randomenv5299 import *
from gym_minigrid.envs.randoms.randomenv3347 import *
from gym_minigrid.envs.randoms.randomenv3471 import *
from gym_minigrid.envs.randoms.randomenv6690 import *
from gym_minigrid.envs.randoms.randomenv8710 import *
from gym_minigrid.envs.randoms.randomenv5498 import *
from gym_minigrid.envs.randoms.randomenv8064 import *
from gym_minigrid.envs.randoms.randomenv8016 import *
from gym_minigrid.envs.randoms.randomenv2000 import *
from gym_minigrid.envs.randoms.randomenv3981 import *
from gym_minigrid.envs.randoms.randomenv9038 import *
from gym_minigrid.envs.randoms.randomenv1957 import *
from gym_minigrid.envs.randoms.randomenv7968 import *
from gym_minigrid.envs.randoms.randomenv7847 import *
from gym_minigrid.envs.randoms.randomenv9323 import *
from gym_minigrid.envs.randoms.randomenv638 import *
from gym_minigrid.envs.randoms.randomenv3161 import *
from gym_minigrid.envs.randoms.randomenv8707 import *
from gym_minigrid.envs.randoms.randomenv9939 import *
from gym_minigrid.envs.randoms.randomenv1624 import *
from gym_minigrid.envs.randoms.randomenv7600 import *
from gym_minigrid.envs.randoms.randomenv637 import *
from gym_minigrid.envs.randoms.randomenv3636 import *
from gym_minigrid.envs.randoms.randomenv6656 import *
from gym_minigrid.envs.randoms.randomenv9711 import *
from gym_minigrid.envs.randoms.randomenv6612 import *
from gym_minigrid.envs.randoms.randomenv2271 import *
from gym_minigrid.envs.randoms.randomenv1542 import *
from gym_minigrid.envs.randoms.randomenv2071 import *
from gym_minigrid.envs.randoms.randomenv67 import *
from gym_minigrid.envs.randoms.randomenv9340 import *
from gym_minigrid.envs.randoms.randomenv1449 import *
from gym_minigrid.envs.randoms.randomenv762 import *
from gym_minigrid.envs.randoms.randomenv5881 import *
from gym_minigrid.envs.randoms.randomenv647 import *
from gym_minigrid.envs.randoms.randomenv6795 import *
from gym_minigrid.envs.randoms.randomenv8857 import *
from gym_minigrid.envs.randoms.randomenv6104 import *
from gym_minigrid.envs.randoms.randomenv5661 import *
from gym_minigrid.envs.randoms.randomenv1573 import *
from gym_minigrid.envs.randoms.randomenv237 import *
from gym_minigrid.envs.randoms.randomenv7182 import *
from gym_minigrid.envs.randoms.randomenv617 import *
from gym_minigrid.envs.randoms.randomenv5997 import *
from gym_minigrid.envs.randoms.randomenv2302 import *
from gym_minigrid.envs.randoms.randomenv9779 import *
from gym_minigrid.envs.randoms.randomenv3805 import *
from gym_minigrid.envs.randoms.randomenv881 import *
from gym_minigrid.envs.randoms.randomenv5873 import *
from gym_minigrid.envs.randoms.randomenv2328 import *
from gym_minigrid.envs.randoms.randomenv4987 import *
from gym_minigrid.envs.randoms.randomenv158 import *
from gym_minigrid.envs.randoms.randomenv8272 import *
from gym_minigrid.envs.randoms.randomenv9330 import *
from gym_minigrid.envs.randoms.randomenv1758 import *
from gym_minigrid.envs.randoms.randomenv5218 import *
from gym_minigrid.envs.randoms.randomenv5802 import *
from gym_minigrid.envs.randoms.randomenv4876 import *
from gym_minigrid.envs.randoms.randomenv5988 import *
from gym_minigrid.envs.randoms.randomenv9224 import *
from gym_minigrid.envs.randoms.randomenv7232 import *
from gym_minigrid.envs.randoms.randomenv5490 import *
from gym_minigrid.envs.randoms.randomenv1812 import *
from gym_minigrid.envs.randoms.randomenv4199 import *
from gym_minigrid.envs.randoms.randomenv3631 import *
from gym_minigrid.envs.randoms.randomenv1251 import *
from gym_minigrid.envs.randoms.randomenv1073 import *
from gym_minigrid.envs.randoms.randomenv3386 import *
from gym_minigrid.envs.randoms.randomenv1033 import *
from gym_minigrid.envs.randoms.randomenv645 import *
from gym_minigrid.envs.randoms.randomenv5923 import *
from gym_minigrid.envs.randoms.randomenv8676 import *
from gym_minigrid.envs.randoms.randomenv9085 import *
from gym_minigrid.envs.randoms.randomenv9600 import *
from gym_minigrid.envs.randoms.randomenv3407 import *
from gym_minigrid.envs.randoms.randomenv5691 import *
from gym_minigrid.envs.randoms.randomenv5617 import *
from gym_minigrid.envs.randoms.randomenv3052 import *
from gym_minigrid.envs.randoms.randomenv7164 import *
from gym_minigrid.envs.randoms.randomenv7780 import *
from gym_minigrid.envs.randoms.randomenv4397 import *
from gym_minigrid.envs.randoms.randomenv7865 import *
from gym_minigrid.envs.randoms.randomenv8301 import *
from gym_minigrid.envs.randoms.randomenv1369 import *
from gym_minigrid.envs.randoms.randomenv1810 import *
from gym_minigrid.envs.randoms.randomenv6630 import *
from gym_minigrid.envs.randoms.randomenv6002 import *
from gym_minigrid.envs.randoms.randomenv5524 import *
from gym_minigrid.envs.randoms.randomenv4796 import *
from gym_minigrid.envs.randoms.randomenv339 import *
from gym_minigrid.envs.randoms.randomenv8576 import *
from gym_minigrid.envs.randoms.randomenv3966 import *
from gym_minigrid.envs.randoms.randomenv9448 import *
from gym_minigrid.envs.randoms.randomenv6874 import *
from gym_minigrid.envs.randoms.randomenv6194 import *
from gym_minigrid.envs.randoms.randomenv8758 import *
from gym_minigrid.envs.randoms.randomenv7955 import *
from gym_minigrid.envs.randoms.randomenv9192 import *
from gym_minigrid.envs.randoms.randomenv9589 import *
from gym_minigrid.envs.randoms.randomenv9474 import *
from gym_minigrid.envs.randoms.randomenv3059 import *
from gym_minigrid.envs.randoms.randomenv6598 import *
from gym_minigrid.envs.randoms.randomenv9128 import *
from gym_minigrid.envs.randoms.randomenv2738 import *
from gym_minigrid.envs.randoms.randomenv1137 import *
from gym_minigrid.envs.randoms.randomenv5545 import *
from gym_minigrid.envs.randoms.randomenv1286 import *
from gym_minigrid.envs.randoms.randomenv2213 import *
from gym_minigrid.envs.randoms.randomenv1376 import *
from gym_minigrid.envs.randoms.randomenv4609 import *
from gym_minigrid.envs.randoms.randomenv8997 import *
from gym_minigrid.envs.randoms.randomenv2745 import *
from gym_minigrid.envs.randoms.randomenv2191 import *
from gym_minigrid.envs.randoms.randomenv9288 import *
from gym_minigrid.envs.randoms.randomenv1449 import *
from gym_minigrid.envs.randoms.randomenv1336 import *
from gym_minigrid.envs.randoms.randomenv8654 import *
from gym_minigrid.envs.randoms.randomenv4094 import *
from gym_minigrid.envs.randoms.randomenv3750 import *
from gym_minigrid.envs.randoms.randomenv4255 import *
from gym_minigrid.envs.randoms.randomenv876 import *
from gym_minigrid.envs.randoms.randomenv8897 import *
from gym_minigrid.envs.randoms.randomenv8328 import *
from gym_minigrid.envs.randoms.randomenv8067 import *
from gym_minigrid.envs.randoms.randomenv7418 import *
from gym_minigrid.envs.randoms.randomenv2188 import *
from gym_minigrid.envs.randoms.randomenv8796 import *
from gym_minigrid.envs.randoms.randomenv2530 import *
from gym_minigrid.envs.randoms.randomenv6113 import *
from gym_minigrid.envs.randoms.randomenv4019 import *
from gym_minigrid.envs.randoms.randomenv6632 import *
from gym_minigrid.envs.randoms.randomenv8093 import *
from gym_minigrid.envs.randoms.randomenv3160 import *
from gym_minigrid.envs.randoms.randomenv6153 import *
from gym_minigrid.envs.randoms.randomenv5805 import *
from gym_minigrid.envs.randoms.randomenv1056 import *
from gym_minigrid.envs.randoms.randomenv318 import *
from gym_minigrid.envs.randoms.randomenv3060 import *
from gym_minigrid.envs.randoms.randomenv3706 import *
from gym_minigrid.envs.randoms.randomenv4017 import *
from gym_minigrid.envs.randoms.randomenv9909 import *
from gym_minigrid.envs.randoms.randomenv8443 import *
from gym_minigrid.envs.randoms.randomenv4869 import *
from gym_minigrid.envs.randoms.randomenv8043 import *
from gym_minigrid.envs.randoms.randomenv4645 import *
from gym_minigrid.envs.randoms.randomenv7523 import *
from gym_minigrid.envs.randoms.randomenv5568 import *
from gym_minigrid.envs.randoms.randomenv1512 import *
from gym_minigrid.envs.randoms.randomenv5210 import *
from gym_minigrid.envs.randoms.randomenv9748 import *
from gym_minigrid.envs.randoms.randomenv3305 import *
from gym_minigrid.envs.randoms.randomenv3588 import *
from gym_minigrid.envs.randoms.randomenv1664 import *
from gym_minigrid.envs.randoms.randomenv1207 import *
from gym_minigrid.envs.randoms.randomenv3014 import *
from gym_minigrid.envs.randoms.randomenv7380 import *
from gym_minigrid.envs.randoms.randomenv2188 import *
from gym_minigrid.envs.randoms.randomenv5857 import *
from gym_minigrid.envs.randoms.randomenv5378 import *
from gym_minigrid.envs.randoms.randomenv8641 import *
from gym_minigrid.envs.randoms.randomenv8336 import *
from gym_minigrid.envs.randoms.randomenv6152 import *
from gym_minigrid.envs.randoms.randomenv409 import *