from gym_minigrid.envs.empty import *
from gym_minigrid.envs.doorkey import *
from gym_minigrid.envs.multiroom import *
from gym_minigrid.envs.fetch import *
from gym_minigrid.envs.gotoobject import *
from gym_minigrid.envs.gotodoor import *
from gym_minigrid.envs.putnear import *
from gym_minigrid.envs.lockedroom import *
from gym_minigrid.envs.playground_v0 import *
from gym_minigrid.envs.redbluedoors import *
from gym_minigrid.envs.unsafe import *
from gym_minigrid.envs.unsafeDoor import *
from gym_minigrid.envs.deadend import *
from gym_minigrid.envs.deadendWater import *
from gym_minigrid.envs.bigEnv import *
from gym_minigrid.envs.firstEvalEnv import *
from gym_minigrid.envs.doorEnv import *
from gym_minigrid.envs.randomenv2a34d45b0 import *
from gym_minigrid.envs.randomenv2801d95a3 import *
from gym_minigrid.envs.randomenv24468ef83 import *
from gym_minigrid.envs.randomenv30922b005 import *
from gym_minigrid.envs.randomenv4bb07939d import *
from gym_minigrid.envs.randomenv2c8a9298d import *
from gym_minigrid.envs.randomenv2933f0697 import *
from gym_minigrid.envs.randomenv316422fd3 import *
from gym_minigrid.envs.randomenv328eb63af import *
from gym_minigrid.envs.randomenv3aa0f4709 import *
from gym_minigrid.envs.randomenv29cc226ca import *
from gym_minigrid.envs.randomenv266564e0f import *
from gym_minigrid.envs.randomenv2e48ef98a import *
from gym_minigrid.envs.randomenv19f15b322 import *
from gym_minigrid.envs.randomenv1b5983713 import *
from gym_minigrid.envs.randomenv28dd10ef4 import *
from gym_minigrid.envs.randomenv27b258685 import *
from gym_minigrid.envs.randomenv227efd36b import *
from gym_minigrid.envs.randomenv26e03af2b import *
from gym_minigrid.envs.randomenv2c32ec172 import *
from gym_minigrid.envs.randomenv111bcf4e2 import *
from gym_minigrid.envs.randomenv1ac286342 import *