from gym_minigrid.envs.empty import *
from gym_minigrid.envs.doorkey import *
from gym_minigrid.envs.multiroom import *
from gym_minigrid.envs.fetch import *
from gym_minigrid.envs.gotoobject import *
from gym_minigrid.envs.gotodoor import *
from gym_minigrid.envs.putnear import *
from gym_minigrid.envs.lockedroom import *
from gym_minigrid.envs.playground_v0 import *
from gym_minigrid.envs.redbluedoors import *
from gym_minigrid.envs.unsafe import *
from gym_minigrid.envs.unsafeDoor import *
from gym_minigrid.envs.deadend import *
from gym_minigrid.envs.deadendWater import *
from gym_minigrid.envs.bigEnv import *
from gym_minigrid.envs.doorEnv import *
from gym_minigrid.envs.doorWaterEnv import *
from gym_minigrid.envs.safety import *
from gym_minigrid.envs.cleaningEnv import *
from gym_minigrid.envs.miniclean import *
from gym_minigrid.envs.bigcleanEnv import *
from gym_minigrid.envs.randoms.randomenv9660 import *
from gym_minigrid.envs.randoms.randomenv2133 import *
from gym_minigrid.envs.wa6_grid6 import *
from gym_minigrid.envs.dnd2_grid6 import *
from gym_minigrid.envs.li_grid6 import *
from gym_minigrid.envs.lighttest import *
from gym_minigrid.envs.randoms.randomenv1147 import *
from gym_minigrid.envs.randoms.randomenv6819 import *
from gym_minigrid.envs.randoms.randomenv7459 import *
from gym_minigrid.envs.randoms.randomenv9120 import *
from gym_minigrid.envs.randoms.randomenv614 import *
from gym_minigrid.envs.randoms.randomenv7925 import *
from gym_minigrid.envs.randoms.randomenv3534 import *
from gym_minigrid.envs.randoms.randomenv9286 import *
from gym_minigrid.envs.randoms.randomenv124 import *
from gym_minigrid.envs.randoms.randomenv9702 import *
from gym_minigrid.envs.randoms.randomenv8843 import *
from gym_minigrid.envs.randoms.randomenv6130 import *
from gym_minigrid.envs.randoms.randomenv9270 import *
from gym_minigrid.envs.randoms.randomenv2594 import *
from gym_minigrid.envs.randoms.randomenv1870 import *
from gym_minigrid.envs.randoms.randomenv8332 import *
from gym_minigrid.envs.randoms.randomenv5375 import *
from gym_minigrid.envs.randoms.randomenv8864 import *
from gym_minigrid.envs.randoms.randomenv4673 import *
from gym_minigrid.envs.randoms.randomenv1476 import *
from gym_minigrid.envs.randoms.randomenv1090 import *
from gym_minigrid.envs.randoms.randomenv426 import *
from gym_minigrid.envs.randoms.randomenv949 import *
from gym_minigrid.envs.randoms.randomenv1094 import *
from gym_minigrid.envs.randoms.randomenv4663 import *
from gym_minigrid.envs.randoms.randomenv6359 import *
from gym_minigrid.envs.randoms.randomenv5557 import *
from gym_minigrid.envs.randoms.randomenv8818 import *
from gym_minigrid.envs.randoms.randomenv1938 import *
from gym_minigrid.envs.randoms.randomenv6417 import *
from gym_minigrid.envs.randoms.randomenv5144 import *
from gym_minigrid.envs.randoms.randomenv8441 import *
from gym_minigrid.envs.randoms.randomenv648 import *
from gym_minigrid.envs.randoms.randomenv8025 import *
from gym_minigrid.envs.randoms.randomenv5744 import *
from gym_minigrid.envs.randoms.randomenv1550 import *
from gym_minigrid.envs.randoms.randomenv9847 import *
from gym_minigrid.envs.randoms.randomenv7767 import *
from gym_minigrid.envs.randoms.randomenv6630 import *
from gym_minigrid.envs.randoms.randomenv8312 import *
from gym_minigrid.envs.randoms.randomenv135 import *
from gym_minigrid.envs.randoms.randomenv4590 import *
from gym_minigrid.envs.randoms.randomenv6030 import *
from gym_minigrid.envs.randoms.randomenv5001 import *
from gym_minigrid.envs.randoms.randomenv7890 import *
from gym_minigrid.envs.randoms.randomenv4900 import *
from gym_minigrid.envs.randoms.randomenv5906 import *
from gym_minigrid.envs.randoms.randomenv7249 import *
from gym_minigrid.envs.randoms.randomenv7482 import *
from gym_minigrid.envs.randoms.randomenv138 import *
from gym_minigrid.envs.randoms.randomenv9822 import *
from gym_minigrid.envs.randoms.randomenv7955 import *
from gym_minigrid.envs.randoms.randomenv8243 import *
from gym_minigrid.envs.randoms.randomenv6680 import *
from gym_minigrid.envs.randoms.randomenv8359 import *
from gym_minigrid.envs.randoms.randomenv7058 import *
from gym_minigrid.envs.randoms.randomenv2472 import *
from gym_minigrid.envs.randoms.randomenv8249 import *
from gym_minigrid.envs.randoms.randomenv3015 import *
from gym_minigrid.envs.randoms.randomenv2256 import *
from gym_minigrid.envs.randoms.randomenv8581 import *
from gym_minigrid.envs.randoms.randomenv6056 import *
from gym_minigrid.envs.randoms.randomenv8949 import *
from gym_minigrid.envs.randoms.randomenv3084 import *
from gym_minigrid.envs.randoms.randomenv2850 import *